FROM node:18 AS angular

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install -g @angular/cli

RUN npm install

EXPOSE 4200

CMD ng serve --host 0.0.0.0 --poll 2000 --disable-host-check

FROM nginx:latest AS ngi

COPY nginx.conf /etc/nginx/conf.d/default.conf