# version: '3.8'
services:
  front:
    image: angularc:latest
    build:
      dockerfile: Dockerfile
      context: .
      target: angular
    # command: ng serve --host 0.0.0.0 --watch
    # ports:
    #   - 4201:80
    environment:
      NODE_ENV: development
    networks:
      - my-proxy-net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
  nginx:
    image: my-nginx
    build: 
      context: .
      dockerfile: dockerfile
      target: ngi
    ports:
      - 4201:80
    networks:
      - my-proxy-net
    depends_on:
      - front

networks:
  my-proxy-net:
    external: true
    name: custom_network
