FROM node:18 AS build

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm install -g @angular/cli

RUN npm install

RUN npm run build

# CMD ["ng", "serve", "--host", "0.0.0.0"]

FROM nginx:latest AS ngi
# Copying compiled code and nginx config to different folder
# NOTE: This path may change according to your project's output folder 
# COPY default.conf.template /etc/nginx/conf.d/default.conf.template
# COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/land-assets /usr/share/nginx/html
# COPY /nginx.conf  /etc/nginx/conf.d/default.conf

# RUN apt-get update
# RUN apt-get install -y vim
# RUN apt-get install -y iputils-ping
# Exposing a port, here it means that inside the container 
# the app will be using Port 80 while running
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
# EXPOSE 80