# version: '3.8'
services:
  service1:
    image: service1:latest
    build:
      context: .
      dockerfile: apps/service1/Dockerfile
      # target: ${NODE_ENV}
      # command: node dist/apps/service1/main
    env_file:
      - ./envs/service1/production.env # Specify the path to your custom env file
      - db.production.env
    ports:
      - 3001:3001
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/dist
      # environment:
      # NODE_ENV: development
    depends_on:
      - db
  sales:
    image: sales:latest
    build:
      context: .
      dockerfile: apps/sales/Dockerfile
      # target: production
      # command: node dist/apps/service1/main
    env_file:
      - ./envs/sale/production.env # Specify the path to your custom env file
      - db.production.env
    ports:
      - 3003:3003
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/dist
      # environment:
      # NODE_ENV: development
    depends_on:
      - db
  auth:
    image: auth:latest
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      # target: production
    # command: npm run start:dev auth
    ports:
      - 3000:3000
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/dist
    env_file:
      - ./envs/auth/production.env
      - db.production.env
      # environment:
      # NODE_ENV: development
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: juninho22
      MYSQL_DATABASE: nest
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
